@port = 5029
@route = login


### LOGIN

POST http://localhost:{{port}}/{{route}}/login
content-type: application/json

{
    "email": "hn@leospabeauty.dk",
    "password": "admin123"
}



### LOGUD

GET http://localhost:{{port}}/{{route}}/logout



### LOGGEDIN?

GET http://localhost:{{port}}/{{route}}/loggedin
