@port = 5029
@route = user

## OBS! 
## Der må kun være 1 forekomst af email i databasen = der kan ikke oprettes en bruger som har samme email som en anden bruger.

### GET - hent alle

GET http://localhost:{{port}}/{{route}}/admin



### GET - hent ud fra ID

GET http://localhost:{{port}}/{{route}}/admin/606ad05332f3eb67309816c8



### POST - opret ny

POST http://localhost:{{port}}/{{route}}/admin
content-type: application/json

{
    "name": "Ny user",
    "email": "ny3@testmail.dk",
    "password": "xxxxxxxxxxx",
    "admin": false
}



### PUT - ret 

PUT http://localhost:{{port}}/{{route}}/admin/606ad05332f3eb67309816c8
content-type: application/json

{
    "name": "Rettet user",
    "email": "rettet@testmail.dk",
    "password": "xxxxxxxxxx",
    "admin": false
}




### DELETE - slet ud fra ID

DELETE http://localhost:{{port}}/{{route}}/admin/606ad05332f3eb67309816c8